// Firebase is loaded lazily so Solo/Local always launch, even if Firebase is unavailable.
let db=null, auth=null, uid=null;
let ref=null, set=null, get=null, onValue=null, update=null, remove=null, onDisconnect=null;
let firebaseReadyPromise=null;
async function ensureFirebase(){
  if(uid && db) return true;
  if(firebaseReadyPromise) return firebaseReadyPromise;
  firebaseReadyPromise=(async()=>{
    try{
      const core=await import('./firebase-init.js');
      db=core.db; auth=core.auth;
      const database=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js');
      ({ref,set,get,onValue,update,remove,onDisconnect}=database);
      const authMod=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js');
      const cred=await authMod.signInAnonymously(auth);
      uid=cred.user.uid;
      return true;
    }catch(err){
      console.error('Firebase:',err);
      firebaseReadyPromise=null;
      onlineMsg('Firebase indisponible. Vérifiez Authentication > Anonymous et la connexion Internet.');
      return false;
    }
  })();
  return firebaseReadyPromise;
}
const $=s=>document.querySelector(s), C=$('#board'),ctx=C.getContext('2d');
let N=9,board=[],turn=1,history=[],captures={1:0,2:0},passes=0,mode='ai',diff='medium',gameOver=false,lastMove=null,aiThinking=false,captureFlash=[];
let roomCode=null,myColor=null,roomUnsub=null,remoteApplying=false; const KOMI=6.5; let audioCtx;
function beep(freq=440,d=.08,type='sine'){if(!$('#soundToggle').checked)return;try{audioCtx ||= new (AudioContext||webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.12,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); function empty(){return Array.from({length:N},()=>Array(N).fill(0))} function clone(b){return b.map(r=>r.slice())} function key(b){return b.flat().join('')} function inside(x,y){return x>=0&&y>=0&&x<N&&y<N} const dirs=[[1,0],[-1,0],[0,1],[0,-1]];
function groupInfo(b,x,y){let col=b[y][x],stack=[[x,y]],seen=new Set(),stones=[],libs=new Set();while(stack.length){let[a,c]=stack.pop(),k=a+','+c;if(seen.has(k))continue;seen.add(k);stones.push([a,c]);for(let[d,e]of dirs){let nx=a+d,ny=c+e;if(!inside(nx,ny))continue;if(b[ny][nx]===0)libs.add(nx+','+ny);else if(b[ny][nx]===col&&!seen.has(nx+','+ny))stack.push([nx,ny])}}return{stones,libs}}
function simulate(b,x,y,col){if(b[y][x])return null;let nb=clone(b);nb[y][x]=col;let removed=[];for(let[d,e]of dirs){let nx=x+d,ny=y+e;if(inside(nx,ny)&&nb[ny][nx]===3-col){let g=groupInfo(nb,nx,ny);if(!g.libs.size)g.stones.forEach(([a,c])=>{nb[c][a]=0;removed.push([a,c])})}}if(groupInfo(nb,x,y).libs.size===0)return null;return{board:nb,removed}}
function legal(x,y,col=turn){let s=simulate(board,x,y,col);if(!s)return null;if(history.length>=2&&key(s.board)===history[history.length-2].key)return null;return s} function save(){history.push({board:clone(board),key:key(board),turn,captures:{...captures},passes,lastMove});if(history.length>120)history.shift()}
const DEFAULT_HINT='Posez une pierre sur une intersection libre.';
function flashHint(msg,ms=1700){let h=$('#hint');h.textContent=msg;h.classList.add('hintAlert');clearTimeout(flashHint._t);flashHint._t=setTimeout(()=>{h.textContent=DEFAULT_HINT;h.classList.remove('hintAlert')},ms)}
function illegalMove(){flashHint('Coup illégal — case occupée, suicide ou répétition (Ko).');C.classList.add('illegal');clearTimeout(illegalMove._t);illegalMove._t=setTimeout(()=>C.classList.remove('illegal'),320)}
async function play(x,y,col=turn,aiAnimated=false){if(gameOver||aiThinking&&!aiAnimated||col!==turn)return;let s=legal(x,y,col);if(!s){beep(130,.12,'square');if(!aiAnimated)illegalMove();return}save();if(aiAnimated&&s.removed.length){let temp=clone(board);temp[y][x]=col;board=temp;lastMove=[x,y];render();await sleep(650);showCapture(s.removed.length);captureFlash=s.removed;render();beep(190,.22,'sawtooth');await sleep(900);captureFlash=[];board=s.board;captures[col]+=s.removed.length;render();await sleep(350)}else{board=s.board;captures[col]+=s.removed.length;lastMove=[x,y];beep(s.removed.length?180:520,s.removed.length?.18:.06,s.removed.length?'sawtooth':'sine')}
lastMove=[x,y];passes=0;turn=3-turn;render();if(mode==='online')syncRoom();if(mode==='ai'&&turn===2&&!gameOver)aiMove()}
function showCapture(n){$('#captureNoticeText').textContent=`${n} pierre${n>1?'s':''} capturée${n>1?'s':''}`;$('#captureNotice').classList.remove('hidden');setTimeout(()=>$('#captureNotice').classList.add('hidden'),1400)}
function pass(){if(gameOver||aiThinking||mode==='online'&&turn!==myColor)return;let who=turn===1?$('#blackName').textContent:$('#whiteName').textContent;save();passes++;lastMove=null;beep(300,.08);if(passes>=2){finish();if(mode==='online')syncRoom();return}flashHint(`${who} passe. Encore une passe pour terminer la partie.`);turn=3-turn;render();if(mode==='online')syncRoom();if(mode==='ai'&&turn===2)aiMove()}
function undo(){if(mode==='online'||!history.length||aiThinking)return;let steps=(mode==='ai'&&turn===1&&history.length>=2)?2:1,h;while(steps--&&history.length)h=history.pop();if(h){board=clone(h.board);turn=h.turn;captures={...h.captures};passes=h.passes;lastMove=h.lastMove;gameOver=false;render()}}
function aiMove(){aiThinking=true;$('#turnText').textContent='IA réfléchit…';setTimeout(async()=>{let moves=[];for(let y=0;y<N;y++)for(let x=0;x<N;x++){let s=legal(x,y,2);if(s){let g=groupInfo(s.board,x,y),center=(N-1)/2,score=Math.random()*2+s.removed.length*20+g.libs.size*.4-Math.hypot(x-center,y-center)*.08;if(diff==='medium')score+=neighborScore(x,y)*.7;if(diff==='hard')score+=neighborScore(x,y)*1.4+Math.min(g.libs.size,4)*2;moves.push({x,y,score})}}moves.sort((a,b)=>b.score-a.score);if(!moves.length){aiThinking=false;pass();return}let pool=diff==='easy'?moves.slice(0,Math.min(20,moves.length)):diff==='medium'?moves.slice(0,5):moves.slice(0,2),m=pool[Math.floor(Math.random()*pool.length)];await play(m.x,m.y,2,true);aiThinking=false},diff==='hard'?850:650)}
function neighborScore(x,y){let s=0;for(let[d,e]of dirs){let a=x+d,c=y+e;if(inside(a,c)){if(board[c][a]===1)s+=1.5;if(board[c][a]===2)s+=1}}return s}
function territory(){let seen=new Set(),t={1:0,2:0};for(let y=0;y<N;y++){for(let x=0;x<N;x++){if(board[y][x]!==0||seen.has(x+','+y))continue;let q=[[x,y]],area=[],border=new Set();while(q.length){let[a,c]=q.pop(),k=a+','+c;if(seen.has(k))continue;seen.add(k);area.push([a,c]);for(let[d,e]of dirs){let nx=a+d,ny=c+e;if(!inside(nx,ny))continue;let v=board[ny][nx];if(v===0&&!seen.has(nx+','+ny))q.push([nx,ny]);else if(v)border.add(v)}}if(border.size===1)t[[...border][0]]+=area.length}}return t}
function finish(){gameOver=true;let t=territory(),bs=t[1]+captures[1],ws=t[2]+captures[2]+KOMI,bn=$('#blackName').textContent,wn=$('#whiteName').textContent,w=bs>ws?bn:wn;$('#winnerTitle').textContent=w+' gagne !';$('#scoreText').textContent=`${bn} : ${bs.toFixed(1)} points\n${wn} : ${ws.toFixed(1)} points\nTerritoire N/B : ${t[1]} / ${t[2]} · Komi : ${KOMI}`;$('#result').classList.remove('hidden');beep(660,.18);setTimeout(()=>beep(880,.3),180);confetti()}
function confetti(){let c=$('#confetti');c.innerHTML='';for(let i=0;i<45;i++){let p=document.createElement('i');p.className='particle';p.style.left=Math.random()*100+'%';p.style.animationDelay=Math.random()*.8+'s';c.appendChild(p)}}
function render(){let landscape=innerWidth>innerHeight,max=landscape?Math.min(Math.max(innerHeight-145,420),760):Math.min(innerWidth-28,760),pad=Math.max(18,max*.055),gap=(max-2*pad)/(N-1);C.width=C.height=max*devicePixelRatio;C.style.width=C.style.height=max+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.fillStyle='#d5a45e';ctx.fillRect(0,0,max,max);ctx.strokeStyle='#302112';ctx.lineWidth=1;for(let i=0;i<N;i++){let p=pad+i*gap;ctx.beginPath();ctx.moveTo(pad,p);ctx.lineTo(max-pad,p);ctx.stroke();ctx.beginPath();ctx.moveTo(p,pad);ctx.lineTo(p,max-pad);ctx.stroke()}let stars=N===9?[2,4,6]:N===13?[3,6,9]:[3,9,15];ctx.fillStyle='#302112';for(let y of stars)for(let x of stars){ctx.beginPath();ctx.arc(pad+x*gap,pad+y*gap,Math.max(2,gap*.07),0,7);ctx.fill()}for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(board[y][x])drawStone(pad+x*gap,pad+y*gap,gap*.43,board[y][x],lastMove&&lastMove[0]===x&&lastMove[1]===y,captureFlash.some(([a,c])=>a===x&&c===y));$('#blackCaptures').textContent=captures[1];$('#whiteCaptures').textContent=captures[2];$('#blackCard').classList.toggle('active',turn===1);$('#whiteCard').classList.toggle('active',turn===2);$('#turnText').textContent=mode==='online'?(turn===myColor?'À vous de jouer':`Tour de ${turn===1?$('#blackName').textContent:$('#whiteName').textContent}`):(turn===1?'Aux Noirs':'Aux Blancs')}
function drawStone(x,y,r,col,last,flash){let g=ctx.createRadialGradient(x-r*.35,y-r*.4,r*.08,x,y,r);if(col===1){g.addColorStop(0,'#555');g.addColorStop(.5,'#171717');g.addColorStop(1,'#000')}else{g.addColorStop(0,'#fff');g.addColorStop(.65,'#e8e4dc');g.addColorStop(1,'#aaa69d')}ctx.fillStyle=g;ctx.shadowColor=flash?'#ffd65a':'#0008';ctx.shadowBlur=flash?r*.9:r*.35;ctx.shadowOffsetY=r*.15;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.shadowColor='transparent';if(last||flash){ctx.strokeStyle=flash?'#ffe57a':col===1?'#e7c06f':'#9b2020';ctx.lineWidth=Math.max(2,r*.12);ctx.beginPath();ctx.arc(x,y,flash?r*.9:r*.27,0,7);ctx.stroke()}}
C.addEventListener('pointerup',e=>{if(gameOver||aiThinking||mode==='ai'&&turn===2||mode==='online'&&turn!==myColor)return;let r=C.getBoundingClientRect(),max=r.width,pad=Math.max(18,max*.055),gap=(max-2*pad)/(N-1),x=Math.round((e.clientX-r.left-pad)/gap),y=Math.round((e.clientY-r.top-pad)/gap);if(inside(x,y)&&Math.hypot((e.clientX-r.left)-(pad+x*gap),(e.clientY-r.top)-(pad+y*gap))<gap*.48)play(x,y)});
function start(){N=+$('#size').value;mode=$('#mode').value;diff=$('#difficulty').value;if(mode==='online'&&!roomCode){onlineMsg('Créez ou rejoignez d’abord un salon.');return}if(mode==='online'){openGame();return}board=empty();turn=1;history=[];captures={1:0,2:0};passes=0;gameOver=false;lastMove=null;$('#blackName').textContent=$('#p1name').value.trim()||'Joueur 1';$('#whiteName').textContent=mode==='ai'?'IA':'Joueur 2';openGame()}
function openGame(){$('#setup').classList.add('hidden');$('#game').classList.remove('hidden');$('#undoBtn').style.display=mode==='online'?'none':'';$('#onlineStatus').classList.toggle('hidden',mode!=='online');render()}
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()} function onlineMsg(t){$('#onlineInfo').textContent=t;$('#onlineInfo').style.display='block'}
async function createRoom(){if(!(await ensureFirebase()))return;roomCode=code();myColor=1;N=+$('#size').value;board=empty();turn=1;captures={1:0,2:0};passes=0;gameOver=false;let name=$('#p1name').value.trim()||'Joueur 1';await set(ref(db,'goRooms/'+roomCode),{hostId:uid,size:N,status:'waiting',players:{[uid]:{name,color:1,connected:true}},state:{board,turn,captures,passes,gameOver,lastMove:null,version:1}});onDisconnect(ref(db,`goRooms/${roomCode}/players/${uid}/connected`)).set(false);showRoom();listenRoom()}
async function joinRoom(){if(!(await ensureFirebase()))return;let c=$('#roomCode').value.trim().toUpperCase();if(!c)return onlineMsg('Entrez le code du salon.');let snap=await get(ref(db,'goRooms/'+c));if(!snap.exists())return onlineMsg('Salon introuvable.');let r=snap.val(),players=r.players||{};if(Object.keys(players).length>=2&&!players[uid])return onlineMsg('Ce salon est complet.');roomCode=c;myColor=players[uid]?.color||2;await update(ref(db,'goRooms/'+c),{status:'playing',[`players/${uid}`]:{name:$('#p1name').value.trim()||'Joueur 2',color:myColor,connected:true}});onDisconnect(ref(db,`goRooms/${c}/players/${uid}/connected`)).set(false);showRoom();listenRoom()}
function showRoom(){$('#shareBox').classList.remove('hidden');$('#roomCodeLabel').textContent=roomCode;$('#roomCode').value=roomCode;onlineMsg(myColor===1?'En attente d’un adversaire…':'Salon rejoint. Vous jouez Blanc.');$('#startBtn').textContent='Entrer dans la partie'}
function listenRoom(){roomUnsub?.();roomUnsub=onValue(ref(db,'goRooms/'+roomCode),snap=>{if(!snap.exists())return;let r=snap.val(),ps=Object.values(r.players||{});if(ps.length===2)onlineMsg('Adversaire connecté — partie prête.');let b=ps.find(p=>p.color===1),w=ps.find(p=>p.color===2);if(b)$('#blackName').textContent=b.name;if(w)$('#whiteName').textContent=w.name;let bar=$('#onlineStatus');if(bar){if(ps.length<2){bar.textContent='En attente d’un adversaire…';bar.classList.remove('hidden')}else{let opp=ps.find(p=>p.color!==myColor);if(opp&&opp.connected===false){bar.textContent='Adversaire déconnecté — en attente de reconnexion…';bar.classList.remove('hidden')}else bar.classList.add('hidden')}}if(r.state){remoteApplying=true;N=r.size||9;board=r.state.board||empty();turn=r.state.turn||1;captures=r.state.captures||{1:0,2:0};passes=r.state.passes||0;gameOver=!!r.state.gameOver;lastMove=r.state.lastMove||null;remoteApplying=false;if(!$('#game').classList.contains('hidden'))render()}})}
function syncRoom(){if(mode!=='online'||!roomCode||remoteApplying)return;set(ref(db,`goRooms/${roomCode}/state`),{board,turn,captures,passes,gameOver,lastMove:lastMove||null,version:Date.now()})}
$('#mode').onchange=()=>{let m=$('#mode').value;$('#difficulty').parentElement.style.display=m==='ai'?'block':'none';$('#onlineSetup').classList.toggle('hidden',m!=='online');$('#startBtn').textContent=m==='online'?'Entrer dans la partie':'Commencer'};$('#createRoom').onclick=createRoom;$('#joinRoom').onclick=joinRoom;$('#shareLink').onclick=async()=>{let url=location.href.split('?')[0]+'?room='+roomCode;try{await navigator.share({title:'GO — invitation',text:`Rejoins ma partie de Go — salon ${roomCode}`,url})}catch{await navigator.clipboard?.writeText(url);onlineMsg('Lien copié.')}};
$('#copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(roomCode);onlineMsg('Code copié : '+roomCode)}catch{onlineMsg('Code du salon : '+roomCode)}};
$('#startBtn').onclick=start;$('#passBtn').onclick=pass;$('#undoBtn').onclick=undo;$('#newBtn').onclick=()=>{if(confirm('Quitter la partie actuelle ?')){$('#game').classList.add('hidden');$('#setup').classList.remove('hidden')}};$('#menuBtn').onclick=()=>$('#drawer').classList.remove('hidden');$('#closeMenu').onclick=()=>$('#drawer').classList.add('hidden');$('#replayBtn').onclick=()=>{$('#result').classList.add('hidden');if(mode==='online'){board=empty();turn=1;captures={1:0,2:0};passes=0;gameOver=false;syncRoom();render()}else start()};$('#homeBtn').onclick=()=>{$('#result').classList.add('hidden');$('#game').classList.add('hidden');$('#setup').classList.remove('hidden')};addEventListener('resize',()=>{if(!$('#game').classList.contains('hidden'))render()});
const q=new URLSearchParams(location.search).get('room');if(q){$('#mode').value='online';$('#mode').dispatchEvent(new Event('change'));$('#roomCode').value=q.toUpperCase();}
